# Global platform for the project
platform :ios, '11.0'

target 'Mental Health' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mental Health
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'IHProgressHUD'
end
